@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue May 10 21:06:57 +0300 2022
=======
REM Generated by Vivado on Tue May 10 19:01:58 +0300 2022
>>>>>>> 602429d015b32bca45360917a2fc737ae11a26b8
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
call xsim Project1Test_behav -key {Behavioral:sim_1:Functional:Project1Test} -tclbatch Project1Test.tcl -view C:/Users/ceza4/corg_pr1/corg_pr1.srcs/sim_1/imports/corg_pr1/alu_module_test_behav.wcfg -log simulate.log
=======
call xsim reg_arf_test_behav -key {Behavioral:sim_1:Functional:reg_arf_test} -tclbatch reg_arf_test.tcl -view C:/Users/Fatih/verilog/corg_pr1/corg_pr1.srcs/sim_1/imports/corg_pr1/alu_module_test_behav.wcfg -log simulate.log
>>>>>>> 602429d015b32bca45360917a2fc737ae11a26b8
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
